### ISSUE TITLE
Language switching loses zoom level and filters

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/servicesadvisor-3.0#86]
Changing the language of the app loses their spot, this is an issue
 - passing the zoom and center point maintained as a basic
 - passing state of the filters is a second problem

See how we can pass the current zoom level and center point on the map when language is changed, even if we cant bring the categorization

**Comment by fmann** [comment]
The map bounding box is now passed on the query string and the map reloaded in the same position/zoom on language switch.

Remembering the state of the filters or reactivating a selected point is currently not feasible because filters and point all using localized identifiers. There is no machine name or lookup method to determine equivalence across languages.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
