### ISSUE TITLE
Tablet display issue 

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/servicesadvisor-3.0#87]
On tablet sizes, clicking pins with many categories, makes the map flicker and move and be un-navigatable. Also clicking the markers in a cluster is twitchy, testing on galaxy tab E

Richard suggests removing the category list from the dropdown, but I think the map needs some attention on mobile in general.

https://www.evernote.com/l/AAhXR2oTpQVJkoWRPcU56fT-N3LJ0XmF1qg

**Comment by PeaceGeeksProjects** [comment]
How about removing all info that is already on the list and keeping only critical info e.g. the top level service, the intake criteria in red, and the address.

**Comment by fmann** [comment]
A few changes are available for testing.

- In the right rail, I am not stacking Hours and Services Provided at tablet widths rather than using a two column layout.
- To prevent jumpiness, I'm setting a max-height on the marker popups. 400px at large sizes, 300px at mobile and tablet. The rest of content is visible by scrolling.
- I also found a broken CSS selector that was trying to adjust the font sizing in the popup. I fixed it, so the popup text is now scaled to match the type size in the right rail.

I didn't add or remove any of content in the popup yet because I wanted to be clear about what is in there. Currently it is:
- Region - Category Name
- Hours
- Activity Details
- Referral Method
- Info Link

Intake criteria and address are not displayed in the popup.

**Comment by mackh** [comment]
Client says the activity details list can be very long, and wants to remove
it. Hours as well. His point is that the side bar shows that detail data,
less in the map pop up is ok. And want to make sure that the sidebar is
visible at mobile sizes. Open to suggestions for a better ux

**Comment by fmann** [comment]
Hours and Activity Details have been removed. That creates a very small pop up just containing:

- Region - Category Name
- Referral Method
- Info Link

@PeaceGeeksProjects suggested adding Intake Criteria and Address to the popup, both of which should typically be short. Thoughts?

**Comment by mackh** [comment]
I like that idea

**Comment by fmann** [comment]
Address and Intake Criteria added to the popups.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
